### ISSUE TITLE
crash on startup with 1.15.2

### ISSUE THREAD

**Issue by endavis** [CerulanLumina/fair-enchanting#1]
The only thing I have loaded is Fabric API.

https://paste.ee/p/JIIiT

**Comment by AltimusX** [comment]
Same crash here, for all versions. 
I've done in depth testing of this issue for compatibility... This just does not work.
https://pastebin.com/g6uYFhsW

**Comment by CerulanLumina** [comment]
Yeah I'm an idiot and released a broken version

**Comment by CerulanLumina** [comment]
Fixed as of v1.1.1 - a89fd8629d591838b907e29b431801baedb00f7e - sorry ;w;
